### ISSUE TITLE
How to create dump for remote db. 

### ISSUE THREAD

**Issue by NareshKukreti12** [Bradleykingz/automated-postgres-backups-with-node#2]
I have applied your code and it is working fine for localhost. But it is always throwing password authentication exceptions when I am trying to create a dump of the remote database.

**Comment by Bradleykingz** [comment]
Hey @NareshKukreti12. 

Did you manage to sort your issue out?

**Comment by NareshKukreti12** [comment]
@Bradleykingz Yes I did
